Repository mokInDang/project_backend, pull requests merged in 2023-04, with the labels that each got.

#220 Refactor/#218/게시글 조회 시 게시글 작성일 반환 리팩토링
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/BoardCreateRequest.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/BoardSelectResponse.java
  src/main/resources/data.sql
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/repository/board/BoardRepositoryTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: refactoring ⚙️

#225 Feature/#221/게시글 삭제 기능 구현
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/exception/GlobalExceptionHandler.java
  src/main/java/mokindang/jubging/project_backend/exception/custom/ForbiddenException.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/BoardIdResponse.java
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: feature 🛠

#219 Feature/#210/전체 게시글 조회 기능 구현
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/repository/board/BoardRepository.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/MultiBoardSelectResponse.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponse.java
  src/test/java/mokindang/jubging/project_backend/repository/board/BoardRepositoryTest.java
Labels: feature 🛠

#224 Feature/#223 마이페이지 조회 구현
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/main/java/mokindang/jubging/project_backend/domain/member/vo/ProfileImage.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/MyPageResponse.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
Labels: feature 🛠, refactoring ⚙️

#230 refactor/#228/게시글 조회 api 패턴 설정 추가
  src/main/java/mokindang/jubging/project_backend/web/config/AuthorizationConfiguration.java
Labels: refactoring ⚙️

#229 Feature/#227/게시글 수정 기능 구현
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/BoardCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/BoardModificationRequest.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/BoardSelectionResponse.java
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: feature 🛠

#233 Feature/#232/게시글 모집 마감 api 구현
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: feature 🛠

#241 Docs/#238/log 설정 변경
  src/main/resources/logback-spring.xml
Labels: docs 📄

#270 refactor : #269 게시글 상세 조회 시 작성자 프로필 url 반환 하도록 변경
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/BoardSelectionResponse.java
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: refactoring ⚙️

#274 Feature/#236/내 정보 수정 구현
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/service/member/request/MyPageEditRequest.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/MyPageResponse.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
Labels: feature 🛠

#282 Refactor/#281/board 엔티티 네이밍 수정
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/controller/board/recruitment/BoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/controller/board/recruitment/RecruitmentBoardController.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/ActivityCategory.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/Content.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/StartingDate.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/Title.java
  src/main/java/mokindang/jubging/project_backend/repository/board/BoardRepository.java
  src/main/java/mokindang/jubging/project_backend/repository/board/RecruitmentBoardRepository.java
  src/main/java/mokindang/jubging/project_backend/scheduler/RecruitmentBoardScheduler.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardSchedulingService.java
  src/main/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/RecruitmentBoardCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/RecruitmentBoardIdResponse.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/RecruitmentBoardSelectionResponse.java
  src/main/resources/data.sql
  src/test/java/mokindang/jubging/project_backend/controller/board/RecruitmentBoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/ActivityCategoryTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/ContentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/StartingDateTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/TitleTest.java
  src/test/java/mokindang/jubging/project_backend/repository/board/RecruitmentRecruitmentBoardRepositoryTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentRecruitmentBoardSchedulingServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentRecruitmentBoardServiceTest.java
Labels: refactoring ⚙️

#280 Refactor/#279/board 서비스 리팩토링
  src/main/java/mokindang/jubging/project_backend/controller/board/recruitment/RecruitmentBoardController.java
  src/main/java/mokindang/jubging/project_backend/controller/board/recruitment/RecruitmentBoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/domain/comment/vo/CommentBody.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/RecruitmentBoardSelectionResponse.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponse.java
  src/main/java/mokindang/jubging/project_backend/web/config/AuthorizationConfiguration.java
  src/test/java/mokindang/jubging/project_backend/controller/board/RecruitmentBoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/ActivityCategoryTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/ContentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/StartingDateTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/TitleTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/BoardSelectionResponseTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponseTest.java
Labels: refactoring ⚙️, PR status : done ✅

#283 Feature/#276/인증 게시판 작성 구현
  src/main/java/mokindang/jubging/project_backend/controller/board/certificationboard/CertificationBoardController.java
  src/main/java/mokindang/jubging/project_backend/controller/board/certificationboard/CertificationBoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/domain/board/certificationboard/CertificationBoard.java
  src/main/java/mokindang/jubging/project_backend/domain/image/Image.java
  src/main/java/mokindang/jubging/project_backend/exception/GlobalExceptionHandler.java
  src/main/java/mokindang/jubging/project_backend/repository/board/certificationboard/CertificationBoardRepository.java
  src/main/java/mokindang/jubging/project_backend/repository/image/ImageRepository.java
  src/main/java/mokindang/jubging/project_backend/service/board/certificationboard/CertificationBoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/certificationboard/request/CertificationBoardCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/service/board/certificationboard/response/CertificationBoardIdResponse.java
  src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
  src/test/java/mokindang/jubging/project_backend/domain/board/certificationboard/CertificationBoardTest.java
Labels: feature 🛠

#289 refactor : #288 LOCATION expose 헤더 설정 추가
  src/main/java/mokindang/jubging/project_backend/web/config/OriginConfig.java
Labels: refactoring ⚙️

#285 Feature/#273/댓글 엔티티 구현
  logs/info.log
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/BoardContentBody.java
  src/main/java/mokindang/jubging/project_backend/domain/comment/Comment.java
  src/main/java/mokindang/jubging/project_backend/domain/comment/ReplyComment.java
  src/main/java/mokindang/jubging/project_backend/domain/comment/vo/CommentBody.java
  src/main/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/RecruitmentBoardCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/RecruitmentBoardSelectionResponse.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponse.java
  src/main/resources/data.sql
  src/test/java/mokindang/jubging/project_backend/controller/board/RecruitmentBoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/BoardContentBodyTest.java
  src/test/java/mokindang/jubging/project_backend/domain/comment/CommentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/comment/ReplyCommentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/comment/vo/CommentBodyTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/BoardSelectionResponseTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponseTest.java
Labels: feature 🛠

#292 refactor : #291 게시글 작성 DTO 변경에따른 수정
  src/main/java/mokindang/jubging/project_backend/domain/board/certificationboard/CertificationBoard.java
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/vo/ContentBody.java
  src/main/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/RecruitmentBoardCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponse.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/BoardSelectionResponseTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponseTest.java
Labels: refactoring ⚙️

#296 Refactor/#286/댓글 및 대댓글 엔티티 리팩토링
  src/main/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/domain/comment/Comment.java
  src/main/java/mokindang/jubging/project_backend/domain/comment/ReplyComment.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/comment/CommentTest.java
Labels: refactoring ⚙️

#297 Feature/#295/인증게시글 수정,삭제 구현
  src/main/java/mokindang/jubging/project_backend/controller/board/certificationboard/CertificationBoardController.java
  src/main/java/mokindang/jubging/project_backend/controller/board/certificationboard/CertificationBoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/domain/board/certificationboard/CertificationBoard.java
  src/main/java/mokindang/jubging/project_backend/repository/image/ImageRepository.java
  src/main/java/mokindang/jubging/project_backend/service/board/certificationboard/CertificationBoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/certificationboard/request/CertificationBoardModificationRequest.java
  src/main/java/mokindang/jubging/project_backend/service/file/FileService.java
  src/main/java/mokindang/jubging/project_backend/service/image/ImageService.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
Labels: feature 🛠

#301 Feature/#300/댓글 작성 api 구현
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentController.java
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/comment/domain/Comment.java
  src/main/java/mokindang/jubging/project_backend/comment/domain/ReplyComment.java
  src/main/java/mokindang/jubging/project_backend/comment/domain/vo/CommentBody.java
  src/main/java/mokindang/jubging/project_backend/comment/repository/CommentRepository.java
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
  src/main/java/mokindang/jubging/project_backend/comment/service/request/CommentCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/RecruitmentBoardService.java
  src/test/java/mokindang/jubging/project_backend/comment/controller/CommentControllerTest.java
  src/test/java/mokindang/jubging/project_backend/comment/service/CommentServiceTest.java
  src/test/java/mokindang/jubging/project_backend/domain/comment/CommentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/comment/ReplyCommentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/comment/vo/CommentBodyTest.java
Labels: feature 🛠

#310 feature : #309 인증게시판 인터셉터 제외 패턴 추가
  src/main/java/mokindang/jubging/project_backend/web/config/AuthorizationConfiguration.java
Labels: feature 🛠

#315 Feature/#313/댓글 삭제 api 구현
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentController.java
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/comment/domain/Comment.java
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
  src/test/java/mokindang/jubging/project_backend/comment/controller/CommentControllerTest.java
  src/test/java/mokindang/jubging/project_backend/comment/service/CommentServiceTest.java
Labels: feature 🛠, PR status : done ✅

#318 Feature/#316/대댓글 작성 api 구현
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentController.java
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/comment/domain/Comment.java
  src/main/java/mokindang/jubging/project_backend/comment/domain/ReplyComment.java
  src/main/java/mokindang/jubging/project_backend/comment/repository/ReplyCommentRepository.java
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
  src/main/java/mokindang/jubging/project_backend/comment/service/request/ReplyCommentCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/comment/service/response/CommentIdResponse.java
  src/test/java/mokindang/jubging/project_backend/comment/controller/CommentControllerTest.java
  src/test/java/mokindang/jubging/project_backend/comment/domain/ReplyCommentTest.java
  src/test/java/mokindang/jubging/project_backend/comment/service/CommentServiceTest.java
Labels: feature 🛠

#326 Feature/#325/대댓글 삭제 api 구현
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentController.java
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
  src/main/java/mokindang/jubging/project_backend/web/config/OpenApiConfig.java
  src/test/java/mokindang/jubging/project_backend/comment/controller/CommentControllerTest.java
  src/test/java/mokindang/jubging/project_backend/comment/service/CommentServiceTest.java
Labels: feature 🛠

#327 bugfix 대댓글 삭제 안되는 문제 해결
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
Labels: bugfix 🐞
