Repository mokInDang/project_backend, pull requests merged in 2023-03, with the labels that each got.

#89 로깅 설정 파일 추가
  src/main/resources/logback-spring.xml
Labels: setting File 📄, PR status : done ✅

#88 ci, cd yml 파일 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/gradle.yml
Labels: setting File 📄, PR status : done ✅

#87 프로파일 설정 변경
  src/main/resources/application.yml
Labels: setting File 📄, PR status : done ✅

#91 Board Write 요청 스웨거 어노테이션 변경
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/web/config/AuthorizationConfiguration.java
Labels: refactoring ⚙️, PR status : done ✅

#93 Feature/#54/member 위치 정보 가져오기 구현
  build.gradle
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/main/java/mokindang/jubging/project_backend/domain/region/vo/Region.java
  src/main/java/mokindang/jubging/project_backend/security/kakao/KaKaoLocal.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/BoardCreateRequest.java
  src/main/java/mokindang/jubging/project_backend/service/member/request/AuthorizationCodeRequest.java
  src/main/java/mokindang/jubging/project_backend/service/member/request/RegionRequest.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/RegionResponse.java
  src/main/resources/static/index.html
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
Labels: feature 🛠, @MinhoKK

#94 로깅 설정 변경
  src/main/resources/logback-spring.xml
Labels: setting File 📄

#96 로깅 설정 변경
  src/main/resources/logback-spring.xml
Labels: setting File 📄

#106 cors 에러 해결을 위한 웹 설정파일 추가
  src/main/java/mokindang/jubging/project_backend/web/config/OpenApiConfig.java
  src/main/java/mokindang/jubging/project_backend/web/config/OriginConfig.java
Labels: setting File 📄

#104 배포 서버 데이터베이스 변경
  src/main/resources/application.yml
Labels: setting File 📄

#127 member의 region 변경 로직추가
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
Labels: feature 🛠, PR status : done ✅

#125 feature/#124/board 엔티티 region 추가
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
Labels: feature 🛠, PR status : done ✅

#135 cors 설정 변경
  build.gradle
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/main/java/mokindang/jubging/project_backend/domain/region/vo/Region.java
  src/main/java/mokindang/jubging/project_backend/security/kakao/KaKaoLocalApi.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/service/member/request/RegionUpdateRequest.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/RegionUpdateResponse.java
  src/main/java/mokindang/jubging/project_backend/web/config/OriginConfig.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
  src/test/java/mokindang/jubging/project_backend/domain/region/vo/RegionTest.java
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
Labels: refactoring ⚙️, PR status : done ✅

#140 Feature/#139/코드 리팩토링
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
  src/main/java/mokindang/jubging/project_backend/service/member/KaKaoLocalApi.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/web/interceptor/LoginCheckInterceptor.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
Labels: refactoring ⚙️, PR status : done ✅

#156 브랜치 전략 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: setting File 📄

#128 Feature/#123/글작성 api 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/main/java/mokindang/jubging/project_backend/domain/region/vo/Region.java
  src/main/java/mokindang/jubging/project_backend/exception/GlobalExceptionHandler.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
  src/main/java/mokindang/jubging/project_backend/service/member/KaKaoLocalApi.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/service/member/request/RegionUpdateRequest.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/RegionUpdateResponse.java
  src/main/java/mokindang/jubging/project_backend/web/config/OriginConfig.java
  src/main/java/mokindang/jubging/project_backend/web/interceptor/LoginCheckInterceptor.java
  src/main/java/mokindang/jubging/project_backend/web/jwt/TokenManager.java
  src/main/resources/logback-spring.xml
  src/main/resources/static/index.html
  src/main/resources/static/kakao_login_medium_narrow.png
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
  src/test/java/mokindang/jubging/project_backend/domain/region/vo/RegionTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
  src/test/java/mokindang/jubging/project_backend/web/jwt/TokenManagerTest.java
Labels: refactoring ⚙️, PR status : done ✅

#162 Feature/#158/게시글 조회 api 구현
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/domain/board/vo/StartingDate.java
  src/main/java/mokindang/jubging/project_backend/domain/region/vo/Region.java
  src/main/java/mokindang/jubging/project_backend/repository/board/BoardRepository.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/response/BoardSelectResponse.java
  src/main/resources/application.yml
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/region/vo/RegionTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: feature 🛠

#166 feature/#165/슬랙_알림_설정
  .github/workflows/cd.yml
Labels: setting File 📄

#167 feature/#165/슬랙_알림_설정
  .github/workflows/cd.yml
Labels: setting File 📄

#163 Refactor/#161/http only 쿠키방식을 이용한 refreshtoken 발급
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/member/request/RefreshTokenRequest.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
Labels: refactoring ⚙️

#175 feature/#174/게시글 조회 시 활동 구분 값 변경
  src/main/java/mokindang/jubging/project_backend/domain/board/ActivityCategory.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
Labels: refactoring ⚙️

#178 Refactor/#168/로그인 api 리팩토링
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/KakaoApiMemberResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/KakaoLoginResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/LoginResponse.java
  src/main/java/mokindang/jubging/project_backend/web/argumentresolver/LoginMemberArgumentResolver.java
  src/main/java/mokindang/jubging/project_backend/web/config/OriginConfig.java
  src/main/java/mokindang/jubging/project_backend/web/interceptor/LoginCheckInterceptor.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
Labels: refactoring ⚙️

#184 refactor : #183 예외 핸들링 추가
  src/main/java/mokindang/jubging/project_backend/exception/GlobalExceptionHandler.java
Labels: refactoring ⚙️

#185 test : #183 테스트 코드 변경
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
Labels: refactoring ⚙️, test ✅

#189 Refactor/#188/컨트롤러 url 매핑 리팩토링
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
Labels: refactoring ⚙️

#187 Refactor/#179/토큰 재발급 리팩토링
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/web/config/OriginConfig.java
  src/main/java/mokindang/jubging/project_backend/web/interceptor/LoginCheckInterceptor.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
Labels: refactoring ⚙️

#193 refactor : #192 excludePathPattern 수정
  src/main/java/mokindang/jubging/project_backend/web/config/AuthorizationConfiguration.java
Labels: refactoring ⚙️

#196 refactor : #192 카카오 토큰 redirect url 수정
  src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
Labels: refactoring ⚙️

#199 refactor : #198 로그아웃 redirect url 수정
  src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
Labels: refactoring ⚙️

#200 refactor : #179 findByMemberId 값 수정
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
Labels: refactoring ⚙️

#201 Refactor/#198/카카오 로그아웃 리팩토링
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/KaKaoOAuth2.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
Labels: refactoring ⚙️

#202 refactor : #198 로그아웃 요청 시 응답코드 302 FOUND 수정
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
Labels: refactoring ⚙️

#206 test : #198 테스트 코드 수정
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
Labels: refactoring ⚙️

#195 feature/#191/게시글_모집_여부_데이터_변경_스케줄러_적용
  src/main/java/mokindang/jubging/project_backend/ProjectBackendApplication.java
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/domain/board/vo/StartingDate.java
  src/main/java/mokindang/jubging/project_backend/repository/board/BoardRepository.java
  src/main/java/mokindang/jubging/project_backend/scheduler/BoardScheduler.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardSchedulingService.java
  src/main/java/mokindang/jubging/project_backend/web/TimeConfig.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/StartingDateTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardSchedulingServiceTest.java
Labels: feature 🛠, PR status : done ✅

#211 Refactor/#169/모든 api 스웨거 적용
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberController.java
  src/main/java/mokindang/jubging/project_backend/controller/member/MemberControllerSwagger.java
Labels: refactoring ⚙️

#215 Refactor/#213/게시글 스케줄링 서비스 리팩토링
  src/main/java/mokindang/jubging/project_backend/repository/board/BoardRepository.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardSchedulingService.java
  src/main/java/mokindang/jubging/project_backend/web/TimeConfig.java
  src/test/java/mokindang/jubging/project_backend/repository/board/BoardRepositoryTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardSchedulingServiceTest.java
Labels: refactoring ⚙️
