Repository mokInDang/project_backend, pull requests merged in 2023-02, with the labels that each got.

#32 Feature/#31/board 엔티티 구현
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/domain/member/Member.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
Labels: feature 🛠, PR status : Working 👨‍💻

#39 Feature/#38/swagger 적용
  build.gradle
  src/main/java/mokindang/jubging/project_backend/web/OpenApiConfig.java
  src/main/resources/application.yml
  src/main/resources/swagger.yml
Labels: setting File 📄, PR status : done ✅

#42 Feature/#37/member service 구현
  build.gradle
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/domain/member/MemberState.java
  src/main/java/mokindang/jubging/project_backend/repository/member/MemberRepository.java
  src/main/java/mokindang/jubging/project_backend/security/kakao/KaKaoOAuth2.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/service/member/dto/KakaoApiMemberResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/dto/LoginResponseDto.java
  src/main/java/mokindang/jubging/project_backend/service/member/dto/LoginStateDto.java
  src/main/resources/static/index.html
  src/main/resources/static/kakao_login_medium_narrow.png
  src/test/java/mokindang/jubging/project_backend/repository/MemberRepositoryTest.java
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
Labels: feature 🛠, PR status : Working 👨‍💻, @MinhoKK

#49 feature/#48/스웨거 적용 및 테스트코드 작성
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/BoardCreateRequest.java
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
Labels: refactoring ⚙️, test ✅, @ch0ijihwan

#51 Feature/#50/board 엔티티 리팩토링
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/domain/board/vo/StartingDate.java
  src/main/java/mokindang/jubging/project_backend/exception/ErrorResponse.java
  src/main/java/mokindang/jubging/project_backend/exception/GlobalExceptionHandler.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/BoardCreateRequest.java
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/ContentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/StartingDateTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/TitleTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: refactoring ⚙️, @ch0ijihwan

#56 Feature/#48/스웨거 적용 및 테스트 코드 추가
  src/main/java/mokindang/jubging/project_backend/controller/board/BoardController.java
  src/main/java/mokindang/jubging/project_backend/domain/board/Board.java
  src/main/java/mokindang/jubging/project_backend/domain/board/vo/StartingDate.java
  src/main/java/mokindang/jubging/project_backend/exception/ErrorResponse.java
  src/main/java/mokindang/jubging/project_backend/exception/GlobalExceptionHandler.java
  src/main/java/mokindang/jubging/project_backend/service/board/BoardService.java
  src/main/java/mokindang/jubging/project_backend/service/board/request/BoardCreateRequest.java
  src/test/java/mokindang/jubging/project_backend/controller/board/BoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/BoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/ContentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/StartingDateTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/vo/TitleTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/BoardServiceTest.java
Labels: refactoring ⚙️, PR status : done ✅, @ch0ijihwan

#57 Feature/#55/package 정리
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/security/kakao/KaKaoOAuth2.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/service/member/request/RefreshTokenRequest.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/JwtResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/KakaoApiMemberResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/LoginResponseDto.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/LoginStateResponse.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
Labels: refactoring ⚙️

#64 feature/#63/CI_개선
  .github/workflows/gradle.yml
Labels: setting File 📄

#68 Feature/#67/dto 수정, 순환 참조 에러 잡기
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/KakaoApiMemberResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/KakaoLoginResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/LoginResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/LoginStateResponse.java
  src/main/java/mokindang/jubging/project_backend/web/interceptor/LoginCheckInterceptor.java
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
Labels: bugfix 🐞, @MinhoKK

#69 refactor : #67 인터셉터 예외 패턴 추가
  src/main/java/mokindang/jubging/project_backend/web/config/AuthorizationConfiguration.java
  src/main/java/mokindang/jubging/project_backend/web/interceptor/LoginCheckInterceptor.java
Labels: refactoring ⚙️, @ch0ijihwan

#74 chore : #36 트리거 브랜치 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: setting File 📄

#72 CD 테스트
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/gradle.yml
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
  src/main/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationController.java
  src/main/java/mokindang/jubging/project_backend/service/authentication/AuthenticationService.java
  src/main/java/mokindang/jubging/project_backend/service/member/MemberService.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/KakaoApiMemberResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/KakaoLoginResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/LoginResponse.java
  src/main/java/mokindang/jubging/project_backend/service/member/response/LoginStateResponse.java
  src/main/java/mokindang/jubging/project_backend/web/config/AuthorizationConfiguration.java
  src/main/java/mokindang/jubging/project_backend/web/interceptor/LoginCheckInterceptor.java
  src/main/resources/application.yml
  src/test/java/mokindang/jubging/project_backend/controller/authentication/AuthenticationControllerTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
Labels: test ✅
