Repository mokInDang/project_backend, pull requests merged in 2023-05, with the labels that each got.

#331 refactor : #109 RuntimeException 에 대한 로깅 설정 추가
  src/main/java/mokindang/jubging/project_backend/exception/GlobalExceptionHandler.java
Labels: refactoring ⚙️

#334 Refactor/#333/여러 게시글 조회 댓글 갯수 포함
  src/main/java/mokindang/jubging/project_backend/comment/domain/Comment.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/response/SummaryBoardResponse.java
  src/main/java/mokindang/jubging/project_backend/web/config/swagger/OpenApiConfig.java
  src/test/java/mokindang/jubging/project_backend/comment/domain/CommentTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
Labels: refactoring ⚙️

#338 Feature/#336/프로필 이미지 업로드 url 분리
  src/main/java/mokindang/jubging/project_backend/file/FileService.java
  src/main/java/mokindang/jubging/project_backend/image/controller/ImageController.java
  src/main/java/mokindang/jubging/project_backend/image/controller/ImageControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/image/service/ImageService.java
  src/main/java/mokindang/jubging/project_backend/image/service/request/ProfileImageDeleteRequest.java
  src/main/java/mokindang/jubging/project_backend/image/service/request/ProfileImageRequest.java
  src/main/java/mokindang/jubging/project_backend/image/service/response/ProfileImageResponse.java
  src/main/java/mokindang/jubging/project_backend/member/controller/MemberController.java
  src/main/java/mokindang/jubging/project_backend/member/controller/MemberControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/member/domain/Member.java
  src/main/java/mokindang/jubging/project_backend/member/domain/vo/ProfileImage.java
  src/main/java/mokindang/jubging/project_backend/member/service/MemberService.java
  src/main/java/mokindang/jubging/project_backend/member/service/request/MyPageEditRequest.java
  src/main/resources/data.sql
  src/test/java/mokindang/jubging/project_backend/comment/domain/CommentTest.java
  src/test/java/mokindang/jubging/project_backend/comment/domain/ReplyCommentTest.java
  src/test/java/mokindang/jubging/project_backend/controller/board/RecruitmentBoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/domain/member/MemberTest.java
  src/test/java/mokindang/jubging/project_backend/member/domain/vo/ProfileImageTest.java
  src/test/java/mokindang/jubging/project_backend/service/authentication/AuthenticationServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponseTest.java
Labels: feature 🛠, refactoring ⚙️

#340 Refactor/#337/댓글 조회 lazy 로딩 활용
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
  src/main/java/mokindang/jubging/project_backend/comment/service/response/CommentSelectionResponse.java
  src/main/resources/data.sql
  src/test/java/mokindang/jubging/project_backend/comment/controller/CommentControllerTest.java
  src/test/java/mokindang/jubging/project_backend/comment/service/CommentServiceTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
Labels: refactoring ⚙️

#343 Feature/#339/인증게시글 이미지 url 분리
  src/main/java/mokindang/jubging/project_backend/certification_board/controller/CertificationBoardController.java
  src/main/java/mokindang/jubging/project_backend/certification_board/controller/CertificationBoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/certification_board/domain/CertificationBoard.java
  src/main/java/mokindang/jubging/project_backend/certification_board/service/CertificationBoardService.java
  src/main/java/mokindang/jubging/project_backend/certification_board/service/request/CertificationBoardCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/certification_board/service/request/CertificationBoardModificationRequest.java
  src/main/java/mokindang/jubging/project_backend/file/FileService.java
  src/main/java/mokindang/jubging/project_backend/image/controller/ImageController.java
  src/main/java/mokindang/jubging/project_backend/image/controller/ImageControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/image/domain/Image.java
  src/main/java/mokindang/jubging/project_backend/image/repository/ImageRepository.java
  src/main/java/mokindang/jubging/project_backend/image/service/ImageService.java
  src/main/java/mokindang/jubging/project_backend/image/service/request/ImageDeleteRequest.java
  src/main/java/mokindang/jubging/project_backend/image/service/request/ImageRequest.java
  src/main/java/mokindang/jubging/project_backend/image/service/request/ProfileImageRequest.java
  src/main/java/mokindang/jubging/project_backend/image/service/response/ImageUrlResponse.java
Labels: feature 🛠, refactoring ⚙️

#345 Feature/#344/이미지 컨트롤러,서비스 리팩토링
  src/main/java/mokindang/jubging/project_backend/certification_board/service/CertificationBoardService.java
  src/main/java/mokindang/jubging/project_backend/image/controller/ImageController.java
  src/main/java/mokindang/jubging/project_backend/image/controller/ImageControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/image/service/ImageService.java
  src/main/java/mokindang/jubging/project_backend/image/service/request/ImageDeleteRequest.java
  src/main/java/mokindang/jubging/project_backend/member/controller/MemberController.java
  src/main/java/mokindang/jubging/project_backend/member/service/MemberService.java
  src/test/java/mokindang/jubging/project_backend/controller/member/MemberControllerTest.java
Labels: refactoring ⚙️

#347 refactor : #346 회원 생성 시 기존 프로필 이미지 url 주입
  src/main/java/mokindang/jubging/project_backend/image/service/ImageService.java
  src/main/java/mokindang/jubging/project_backend/member/domain/vo/ProfileImage.java
  src/main/java/mokindang/jubging/project_backend/member/service/response/MyPageResponse.java
  src/main/resources/data.sql
  src/test/java/mokindang/jubging/project_backend/service/member/MemberServiceTest.java
Labels: refactoring ⚙️

#342 Refactor/#341/구인게시글 작성시 활동장소 좌표를 입력 받도록 변경
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/vo/Coordinate.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/vo/Latitude.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/vo/Longitude.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/vo/Place.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/request/RecruitmentBoardCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/response/MeetingPlaceResponse.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/response/RecruitmentBoardSelectionResponse.java
  src/test/java/mokindang/jubging/project_backend/comment/domain/CommentTest.java
  src/test/java/mokindang/jubging/project_backend/controller/board/RecruitmentBoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/recruitment_board/domain/vo/CoordinateTest.java
  src/test/java/mokindang/jubging/project_backend/recruitment_board/domain/vo/LatitudeTest.java
  src/test/java/mokindang/jubging/project_backend/recruitment_board/domain/vo/LongitudeTest.java
  src/test/java/mokindang/jubging/project_backend/repository/board/RecruitmentRecruitmentBoardRepositoryTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardServiceTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/BoardSelectionResponseTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/response/SummaryBoardResponseTest.java
Labels: refactoring ⚙️

#349 Refactor/#348/구인 게시글 수정 시 좌표와 상세 주소를 입력 받도록 변경
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/request/BoardModificationRequest.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/request/MeetingPlaceCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/request/MeetingPlaceModificationRequest.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/request/RecruitmentBoardCreationRequest.java
  src/test/java/mokindang/jubging/project_backend/controller/board/RecruitmentBoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardServiceTest.java
Labels: refactoring ⚙️

#354 Feature/#350/지역 게시글 마커 조회 기능 구현
  src/main/java/mokindang/jubging/project_backend/recruitment_board/controller/RecruitmentBoardController.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/controller/RecruitmentBoardControllerSwagger.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/repository/RecruitmentBoardRepository.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/response/BoardPlaceMarkerResponse.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/response/MeetingPlaceResponse.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/response/MultiBoardPlaceSelectionResponse.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/response/MultiBoardSelectionResponse.java
  src/main/resources/data.sql
  src/test/java/mokindang/jubging/project_backend/controller/board/RecruitmentBoardControllerTest.java
  src/test/java/mokindang/jubging/project_backend/repository/board/RecruitmentRecruitmentBoardRepositoryTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardServiceTest.java
Labels: feature 🛠

#356 refactor : #355 모집게시글 전체조회 작성일 기준 정렬
  src/main/java/mokindang/jubging/project_backend/recruitment_board/repository/RecruitmentBoardRepository.java
Labels: refactoring ⚙️

#352 Refactor/#351/comment 테스트 코드 작성
  src/test/java/mokindang/jubging/project_backend/comment/domain/CommentTest.java
  src/test/java/mokindang/jubging/project_backend/comment/domain/vo/CommentBodyTest.java
Labels: refactoring ⚙️, test ✅

#357 refactor : #355 모집게시글 전체조회 작성일 기준 내림차순
  src/main/java/mokindang/jubging/project_backend/recruitment_board/repository/RecruitmentBoardRepository.java
Labels: refactoring ⚙️

#359 Feature/#358/타지역 게시글 댓글 조회 제한 기능 추가
  src/main/java/mokindang/jubging/project_backend/comment/controller/CommentController.java
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/RecruitmentBoardService.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardServiceTest.java
Labels: feature 🛠

#361 Refactor/#360/상세 게시글 조회 시 댓글 카운트 반환 로직 변경
  src/main/java/mokindang/jubging/project_backend/comment/service/response/MultiCommentSelectionResponse.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/RecruitmentBoardService.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/request/MeetingPlaceCreationRequest.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/request/MeetingPlaceModificationRequest.java
Labels: refactoring ⚙️

#362 Refactor/#360/상세 게시글 조회 시 댓글 카운트 반환 로직 변경
  src/main/java/mokindang/jubging/project_backend/comment/service/response/CommentSelectionResponse.java
  src/main/java/mokindang/jubging/project_backend/comment/service/response/MultiCommentSelectionResponse.java
Labels: refactoring ⚙️

#365 Refactor/#364/타지역 댓글 조회시 댓글 조회 및 작성 여부 반환 하도록 변경
  src/main/java/mokindang/jubging/project_backend/comment/service/CommentService.java
  src/main/java/mokindang/jubging/project_backend/comment/service/response/MultiCommentSelectionResponse.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/domain/RecruitmentBoard.java
  src/main/java/mokindang/jubging/project_backend/recruitment_board/service/RecruitmentBoardService.java
  src/test/java/mokindang/jubging/project_backend/comment/controller/CommentControllerTest.java
  src/test/java/mokindang/jubging/project_backend/domain/board/recruitment/RecruitmentBoardTest.java
  src/test/java/mokindang/jubging/project_backend/service/board/RecruitmentBoardServiceTest.java
Labels: refactoring ⚙️
